version: '3.8'

services:
  blog:
    image: hominsu/blog:latest
    container_name: blog
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "3000:3000"
    networks:
      net:
        aliases:
          - blog

networks:
  net:
    driver: bridge
