name: Docker Deploy

on:
  push:
    tags: ['*.*.*']

jobs:
  dockerize:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/hominsu/postgresql
            hominsu/postgresql
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=auto
          bake-target: metadata

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: 'lab:latest'
          driver: cloud
          endpoint: 'hominsu/builder'

      - name: Build and Push
        id: bake
        uses: docker/bake-action@v5
        with:
          files: |
            docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: blog
          push: true
        env:
          NEXT_PUBLIC_ALGOLIA_APIKEY: ${{ secrets.NEXT_ALGOLIA_APIKEY }}
          NEXT_PUBLIC_ALGOLIA_APPID: ${{ secrets.NEXT_ALGOLIA_APPID }}
          NEXT_PUBLIC_ALGOLIA_INDEX_NAME: ${{ secrets.NEXT_ALGOLIA_INDEX_NAME }}
          NEXT_PUBLIC_GISCUS_CATEGORY: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY }}
          NEXT_PUBLIC_GISCUS_CATEGORY_ID: ${{ secrets.NEXT_PUBLIC_GISCUS_CATEGORY_ID }}
          NEXT_PUBLIC_GISCUS_REPO: ${{ secrets.NEXT_PUBLIC_GISCUS_REPO }}
          NEXT_PUBLIC_GISCUS_REPOSITORY_ID: ${{ secrets.NEXT_PUBLIC_GISCUS_REPOSITORY_ID }}
